from pathlib import Path
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKDOWN_MARKER = "<!-- Generated by scripts/sync_adapters.py; do not edit by hand. -->"
TOKEN_PATTERN = re.compile(r"llmw_[A-Za-z0-9_=-]{12,}")


def copy_path(src: Path, dst: Path) -> None:
    if src.is_dir():
        shutil.copytree(
            src,
            dst,
            ignore=shutil.ignore_patterns(".git", ".idea", "__pycache__"),
            dirs_exist_ok=True,
        )
        return

    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


class SourceLayoutTests(unittest.TestCase):
    def test_version_and_constants_exist(self):
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        constants = json.loads((ROOT / "src/shared/constants.json").read_text(encoding="utf-8"))
        self.assertRegex(version, r"^\d+\.\d+\.\d+$")
        self.assertEqual(constants["version"], version)
        self.assertEqual(constants["plugin_name"], "llm-wiki-client")
        self.assertEqual(constants["marketplace_name"], "llm-wiki-cloud")
        self.assertEqual(constants["repository"], "AndyKong2020/LLM-Wiki-Marketplace-Cloud")
        self.assertEqual(constants["ref"], "main")
        self.assertEqual(constants["mcp_url"], "https://wiki.andykong.top/mcp")
        self.assertEqual(constants["backflow_upload_url"], "https://wiki.andykong.top/upload/backflow")
        self.assertEqual(constants["version_manifest_url"], "https://wiki.andykong.top/plugin/llm-wiki-client/version.json")

    def test_pin_block_template_has_platform_slots(self):
        text = (ROOT / "src/shared/pin-block.md.tmpl").read_text(encoding="utf-8")
        self.assertIn("{{mcp_url}}", text)
        self.assertIn("{{query_skill_name}}", text)
        self.assertIn("{{wiki_search_tool}}", text)
        self.assertIn("{{wiki_get_page_tool}}", text)


class TemplateInventoryTests(unittest.TestCase):
    def test_skill_templates_do_not_reference_legacy_query_skill(self):
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("llm-wiki-query", text, path.relative_to(ROOT))

    def test_shared_skill_templates_are_platform_neutral(self):
        forbidden_phrases = [
            "当前 Claude Code 项目目录",
            "/plugin update",
            "/reload-plugins",
            "claude mcp add",
        ]
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            for phrase in forbidden_phrases:
                with self.subTest(path=path.relative_to(ROOT), phrase=phrase):
                    self.assertNotIn(phrase, text)

    def test_mount_template_uses_shared_pin_block_contract(self):
        mount_text = (ROOT / "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl").read_text(encoding="utf-8")
        sync_text = (ROOT / "scripts/sync_adapters.py").read_text(encoding="utf-8")
        pin_block_text = (ROOT / "src/shared/pin-block.md.tmpl").read_text(encoding="utf-8")
        self.assertIn("src/shared/pin-block.md.tmpl", sync_text)
        self.assertIn("{{pin_block}}", mount_text)
        self.assertIn("写入或更新这段 block", mount_text)
        self.assertNotIn("发布时预渲染", mount_text)
        self.assertNotIn("共享 pin block 必须使用这些 slot", mount_text)
        self.assertTrue(set(re.findall(r"{{[a-zA-Z0-9_]+}}", pin_block_text)))

    def test_skill_templates_have_no_todo_markers(self):
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            allowed = "TODO:链接下探" if path.name == "SKILL.md.tmpl" and path.parent.name == "llm-wiki-cloud-query" else ""
            self.assertNotIn("TODO", text.replace(allowed, ""), path.relative_to(ROOT))

    def test_required_templates_exist(self):
        required = [
            "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-query/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-backflow/SKILL.md.tmpl",
            "src/skills/session-extractor/SKILL.md.tmpl",
            "src/skills/session-extractor/scripts/extract.py",
            "src/skills/session-extractor/scripts/sessionlog/adapters/claude.py",
            "src/skills/session-extractor/scripts/sessionlog/adapters/codex.py",
            "src/skills/session-extractor/scripts/sessionlog/adapters/opencode.py",
            "platforms/claude/marketplace.json.tmpl",
            "platforms/claude/plugin.json.tmpl",
            "platforms/codex/marketplace.json.tmpl",
            "platforms/codex/plugin.json.tmpl",
            "platforms/opencode/opencode.json.tmpl",
        ]
        for rel in required:
            with self.subTest(rel=rel):
                path = ROOT / rel
                self.assertTrue(path.exists(), rel)
                self.assertGreater(path.stat().st_size, 80, rel)

    def test_no_command_source_or_adapter_dirs(self):
        forbidden = [
            "src/commands",
            "plugins/llm-wiki-client-claude/commands",
            "plugins/llm-wiki-client-codex/commands",
            "plugins/llm-wiki-client-opencode/commands",
        ]
        for rel in forbidden:
            with self.subTest(rel=rel):
                self.assertFalse((ROOT / rel).exists(), rel)

    def test_opencode_scripts_are_direct_sources(self):
        for rel in [
            "plugins/llm-wiki-client-opencode/bootstrap.sh",
            "plugins/llm-wiki-client-opencode/install-opencode.sh",
            "plugins/llm-wiki-client-opencode/uninstall.sh",
        ]:
            with self.subTest(rel=rel):
                text = (ROOT / rel).read_text(encoding="utf-8")
                self.assertTrue(text.startswith("#!/usr/bin/env bash\n"), rel)
                self.assertNotIn("Generated by scripts/sync_adapters.py", text)

    def test_skill_templates_have_required_frontmatter_slots(self):
        for rel in [
            "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-query/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-backflow/SKILL.md.tmpl",
            "src/skills/session-extractor/SKILL.md.tmpl",
        ]:
            text = (ROOT / rel).read_text(encoding="utf-8")
            self.assertIn("version: {{version}}", text)
            self.assertIn("name:", text)
            self.assertIn("description:", text)

class SyncAdaptersTests(unittest.TestCase):
    FIXTURE_PATHS = [
        "VERSION",
        "src",
        "platforms",
        "scripts/sync_adapters.py",
        ".claude-plugin",
        "plugins/llm-wiki-client-claude/.claude-plugin",
        "plugins/llm-wiki-client-claude/.mcp.json",
        "plugins/llm-wiki-client-claude/skills",
        "plugins/llm-wiki-client-codex",
        "plugins/llm-wiki-client-opencode",
    ]

    def copy_repo_fixture(self) -> Path:
        temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(temp_dir.cleanup)
        temp_root = Path(temp_dir.name)
        for rel in self.FIXTURE_PATHS:
            copy_path(ROOT / rel, temp_root / rel)
        return temp_root

    def copy_script_only_fixture(self) -> Path:
        temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(temp_dir.cleanup)
        script_root = Path(temp_dir.name)
        copy_path(ROOT / "scripts/sync_adapters.py", script_root / "scripts/sync_adapters.py")
        return script_root

    def run_sync(self, temp_root: Path | None = None) -> Path:
        temp_root = temp_root or self.copy_repo_fixture()
        env = os.environ.copy()
        env["LLM_WIKI_REPO_ROOT"] = str(temp_root)
        subprocess.run([sys.executable, "scripts/sync_adapters.py"], cwd=temp_root, env=env, check=True)
        self.sync_root = temp_root
        return temp_root

    def test_sync_uses_env_root_when_script_path_is_outside_repo_fixture(self):
        temp_root = self.copy_repo_fixture()
        script_root = self.copy_script_only_fixture()
        env = os.environ.copy()
        env["LLM_WIKI_REPO_ROOT"] = str(temp_root)

        subprocess.run(
            [sys.executable, str(script_root / "scripts/sync_adapters.py")],
            cwd=script_root,
            env=env,
            check=True,
        )

        self.assertTrue((temp_root / "plugins/llm-wiki-client-opencode/opencode.json").exists())
        self.assertFalse((script_root / "plugins/llm-wiki-client-opencode/opencode.json").exists())

    def test_run_sync_does_not_create_live_stale_test_paths(self):
        live_test_paths = [
            ROOT / ".agents/unmanaged/sentinel.txt",
            ROOT / "plugins/llm-wiki-client-claude/skills/stale-generated/SKILL.md",
            ROOT / "plugins/llm-wiki-client-claude/skills/stale-user/SKILL.md",
        ]
        live_state = {path: path.read_bytes() if path.is_file() else None for path in live_test_paths}

        temp_root = self.run_sync()

        self.assertNotEqual(temp_root.resolve(), ROOT.resolve())
        for path, original_content in live_state.items():
            with self.subTest(path=path.relative_to(ROOT)):
                current_content = path.read_bytes() if path.is_file() else None
                self.assertEqual(current_content, original_content)

    def test_sync_preserves_unmanaged_agents_files(self):
        temp_root = self.copy_repo_fixture()
        sentinel = temp_root / ".agents/unmanaged/sentinel.txt"
        sentinel_text = "unmanaged agent state must survive sync\n"
        sentinel.parent.mkdir(parents=True, exist_ok=True)
        sentinel.write_text(sentinel_text, encoding="utf-8")

        self.run_sync(temp_root)

        self.assertTrue(sentinel.exists())
        self.assertEqual(sentinel.read_text(encoding="utf-8"), sentinel_text)

    def test_sync_removes_stale_generated_marked_files(self):
        temp_root = self.copy_repo_fixture()
        stale_generated = temp_root / "plugins/llm-wiki-client-claude/skills/stale-generated/SKILL.md"
        stale_user = temp_root / "plugins/llm-wiki-client-claude/skills/stale-user/SKILL.md"
        stale_generated.parent.mkdir(parents=True, exist_ok=True)
        stale_user.parent.mkdir(parents=True, exist_ok=True)
        stale_generated.write_text(f"{GENERATED_MARKDOWN_MARKER}\n\nold generated skill\n", encoding="utf-8")
        stale_user.write_text("user managed skill\n", encoding="utf-8")

        self.run_sync(temp_root)

        self.assertFalse(stale_generated.exists())
        self.assertTrue(stale_user.exists())

    def test_sync_removes_stale_generated_skill_files(self):
        temp_root = self.copy_repo_fixture()
        stale_skill = temp_root / "plugins/llm-wiki-client-claude/skills/stale/SKILL.md"
        stale_skill.parent.mkdir(parents=True, exist_ok=True)
        stale_skill.write_text(f"{GENERATED_MARKDOWN_MARKER}\n\nold generated skill\n", encoding="utf-8")

        self.run_sync(temp_root)

        self.assertFalse(stale_skill.exists())

    def test_sync_generates_all_platform_entrypoints(self):
        temp_root = self.run_sync()
        required = [
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "plugins/llm-wiki-client-claude/.claude-plugin/plugin.json",
            "plugins/llm-wiki-client-claude/.mcp.json",
            "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json",
            "plugins/llm-wiki-client-codex/.mcp.json",
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-backflow/SKILL.md",
            "plugins/llm-wiki-client-claude/skills/session-extractor/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-backflow/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/session-extractor/SKILL.md",
            "plugins/llm-wiki-client-opencode/opencode.json",
            "plugins/llm-wiki-client-opencode/bootstrap.sh",
            "plugins/llm-wiki-client-opencode/install-opencode.sh",
            "plugins/llm-wiki-client-opencode/uninstall.sh",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-backflow/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/session-extractor/SKILL.md",
        ]
        for rel in required:
            with self.subTest(rel=rel):
                self.assertTrue((temp_root / rel).exists(), rel)

    def test_session_extractor_support_files_are_copied(self):
        temp_root = self.run_sync()
        for platform in ["claude", "codex", "opencode"]:
            skill_root = temp_root / f"plugins/llm-wiki-client-{platform}/skills/session-extractor"
            with self.subTest(platform=platform):
                self.assertTrue((skill_root / "SKILL.md").exists())
                self.assertTrue((skill_root / "scripts/extract.py").exists())
                self.assertTrue((skill_root / "scripts/sessionlog/render.py").exists())
                self.assertFalse((skill_root / "scripts/tests").exists())

    def test_backflow_uses_session_extractor_only_as_fallback(self):
        temp_root = self.run_sync()
        forbidden = [
            "session_extractor_script",
            "LLM_WIKI_SESSION_EXTRACTOR",
            "cannot locate bundled session-extractor",
            "rglob(",
        ]
        for platform in ["claude", "codex", "opencode"]:
            rel = f"plugins/llm-wiki-client-{platform}/skills/llm-wiki-cloud-backflow/SKILL.md"
            text = (temp_root / rel).read_text(encoding="utf-8")
            with self.subTest(platform=platform):
                self.assertIn(".agents-log/summary/", text)
                self.assertIn("在 workspace 中查找 `.agents-log/summary/`", text)
                self.assertIn("没有找到相关 `.agents-log` summary", text)
                self.assertIn("session-extractor", text)
                self.assertIn("archive 的 `workspace/agents-log/`", text)
                self.assertIn("同形态", text)
                self.assertIn("执行 `session-extractor` 时使用 structured 模式", text)
                self.assertIn("默认只保留 `workspace/agents-log/summary/`", text)
                self.assertIn("`workspace/agents-log/meta/` 默认不纳入 archive/upload", text)
                self.assertIn("└── workspace/\n    └── agents-log/\n        └── summary/", text)
                self.assertNotIn("workspace/session-extractor/", text)
                self.assertNotIn("Session Extractor Trace", text)
                self.assertNotIn("不要在 backflow 中复写", text)
                self.assertNotIn("定位、解析或渲染逻辑", text)
                self.assertNotIn("原逻辑", text)
                self.assertNotIn("fallback 生成且需要保留详细/外溢材料时可存在", text)
                self.assertNotIn("└── workspace/\n    ├── agents-log/\n    │   └── summary/", text)
                for snippet in forbidden:
                    self.assertNotIn(snippet, text)

    def test_backflow_exports_git_evidence_only_when_task_used_git(self):
        temp_root = self.run_sync()
        for platform in ["claude", "codex", "opencode"]:
            rel = f"plugins/llm-wiki-client-{platform}/skills/llm-wiki-cloud-backflow/SKILL.md"
            text = (temp_root / rel).read_text(encoding="utf-8")
            with self.subTest(platform=platform):
                self.assertIn("任务中实际使用过 git", text)
                self.assertIn("不要因为 workspace 是 git 仓库就自动导出 git 证据", text)
                self.assertIn("不要复制 `.git/` 目录", text)
                self.assertIn("`workspace/git/`", text)
                self.assertIn("候选项，不要求全部保存", text)
                self.assertIn("`head.txt`", text)
                self.assertIn("`status.txt`", text)
                self.assertIn("`diff.patch`", text)
                self.assertIn("`diff-cached.patch`", text)
                self.assertIn("`recent-log.txt`", text)
                self.assertIn("`git status --short --branch`", text)
                self.assertIn("`git diff --no-ext-diff -- .`", text)
                self.assertIn("`git diff --cached --no-ext-diff -- .`", text)
                self.assertIn("`git log --oneline --decorate -n 20`", text)
                self.assertIn("`.git/` 目录默认不纳入 archive/upload", text)
                self.assertIn("如果 URL 含凭据、token 或私有入口，省略或改写后再归档", text)
                self.assertNotIn("如果 workspace 是 git 仓库，不复制 `.git/` 目录；按需创建 `workspace/git/`", text)

    def test_embedded_session_extractor_tests_pass(self):
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "unittest",
                "discover",
                "-s",
                "src/skills/session-extractor/scripts/tests",
                "-v",
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_sync_replaces_all_template_variables(self):
        temp_root = self.run_sync()
        version = (temp_root / "VERSION").read_text(encoding="utf-8").strip()
        generated = [
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        ]
        for rel in generated:
            path = temp_root / rel
            self.assertTrue(path.exists(), rel)
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("{{", text)
            self.assertNotIn("}}", text)
            self.assertIn(f"version: {version}", text)
            self.assertIn("https://wiki.andykong.top/mcp", text)

    def test_sync_generates_platform_specific_instruction_targets(self):
        temp_root = self.run_sync()
        claude_mount = (temp_root / "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        codex_mount_path = temp_root / "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md"
        self.assertTrue(codex_mount_path.exists())
        codex_mount = codex_mount_path.read_text(encoding="utf-8")
        opencode_mount = (temp_root / "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("CLAUDE.md", claude_mount)
        self.assertIn("AGENTS.md", codex_mount)
        self.assertIn("AGENTS.md", opencode_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", codex_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", opencode_mount)

    def test_mount_update_guidance_is_platform_specific(self):
        temp_root = self.run_sync()
        claude_mount = (temp_root / "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        codex_mount = (temp_root / "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        opencode_mount = (temp_root / "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")

        self.assertIn("/plugin marketplace update llm-wiki-cloud", claude_mount)
        self.assertIn("/plugin update llm-wiki-client@llm-wiki-cloud", claude_mount)
        self.assertIn("plugin_version_current 低于 1.2.0", claude_mount)
        self.assertIn("`/plugins`", claude_mount)
        self.assertIn("/plugin install llm-wiki-client@llm-wiki-cloud", claude_mount)
        self.assertNotIn("/plugin marketplace remove llm-wiki-cloud", claude_mount)
        self.assertNotIn("/plugin marketplace add AndyKong2020/LLM-Wiki-Marketplace-Cloud", claude_mount)

        self.assertIn("codex plugin marketplace upgrade llm-wiki-cloud", codex_mount)
        self.assertIn("codex plugin remove llm-wiki-client@llm-wiki-cloud", codex_mount)
        self.assertIn("codex plugin add llm-wiki-client@llm-wiki-cloud", codex_mount)

        self.assertIn("plugins/llm-wiki-client-opencode/bootstrap.sh | bash", opencode_mount)

        for text in [codex_mount, opencode_mount]:
            self.assertNotIn("低于 1.2.0", text)
            self.assertNotIn("`/plugins`", text)

    def test_sync_embeds_pre_rendered_pin_block_in_mount_skills(self):
        temp_root = self.run_sync()
        generated = {
            "claude": temp_root / "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "codex": temp_root / "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "opencode": temp_root / "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        }
        for platform, path in generated.items():
            with self.subTest(platform=platform):
                text = path.read_text(encoding="utf-8")
                self.assertIn("<!-- LLM-WIKI:BEGIN -->", text)
                self.assertIn("<!-- LLM-WIKI:END -->", text)
                self.assertIn("写入或更新这段 block", text)
                self.assertNotIn("发布时预渲染", text)
                self.assertNotIn("共享 pin block 必须使用这些 slot", text)

    def test_sync_generates_codex_specific_skill_root(self):
        temp_root = self.run_sync()
        codex_manifest = json.loads(
            (temp_root / "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json").read_text(encoding="utf-8")
        )
        self.assertIn("skills", codex_manifest)
        self.assertEqual(codex_manifest["skills"], "./skills/")
        self.assertFalse((temp_root / "plugins/llm-wiki-client-codex/codex").exists())
        self.assertFalse((temp_root / "plugins/llm-wiki-client-codex/commands").exists())

        codex_mount_path = temp_root / "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md"
        self.assertTrue(codex_mount_path.exists())
        codex_mount = codex_mount_path.read_text(encoding="utf-8")
        self.assertIn("AGENTS.md", codex_mount)
        self.assertIn("cann-infer-wiki-cloud wiki_search", codex_mount)
        self.assertNotIn("CLAUDE.md", codex_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", codex_mount)

    def test_sync_generates_valid_json_manifests(self):
        temp_root = self.run_sync()
        for rel in [
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "plugins/llm-wiki-client-claude/.claude-plugin/plugin.json",
            "plugins/llm-wiki-client-claude/.mcp.json",
            "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json",
            "plugins/llm-wiki-client-codex/.mcp.json",
            "plugins/llm-wiki-client-opencode/opencode.json",
        ]:
            with self.subTest(rel=rel):
                json.loads((temp_root / rel).read_text(encoding="utf-8"))

    def test_sync_preserves_markdown_frontmatter(self):
        temp_root = self.run_sync()
        for rel in [
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        ]:
            text = (temp_root / rel).read_text(encoding="utf-8")
            with self.subTest(rel=rel):
                self.assertTrue(text.startswith("---\n"), rel)
                self.assertNotIn("Generated by scripts/sync_adapters.py", text)


if __name__ == "__main__":
    unittest.main()
